title: Build Things Together
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: x
baseurl: "http://billmills.github.io/blog"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
